In [21]:
import numpy as np

In [22]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,0,0,1]).T
X.shape,Y.shape

((4, 2), (4,))

In [23]:
def sig(z):
    return 1/(1+np.exp(-z))

# Forward Propagation with No Hidden Layer

In [24]:

weights = 2*np.random.random((2,1))-1  #pass shape as argument 
bias = 2*np.random.random(1)-1
weights,bias

(array([[-0.19004461],
        [ 0.66431794]]),
 array([0.64526536]))

In [33]:

output0 = X
output = sig(np.dot(output0,weights)+bias)
output

array([[0.65594273],
       [0.78744342],
       [0.6118798 ],
       [0.75390314]])

# Forward Propagation with Hidden Layer

In [18]:
wh = 2*np.random.random((2,2))-1
bh = 2 * np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1

In [20]:
outuput0= X
outputHidden = sig(np.dot(output0,wh)+bh)
output = sig(np.dot(outputHidden,wo)+bo)
output

array([[0.49121586],
       [0.4728831 ],
       [0.4833224 ],
       [0.46704683]])