In [3]:
import numpy as np

In [119]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

## Deriving derivative of sigmoid(z)

<br>

<div style="display:flex">
    <img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/1.png?raw=true" style="height:445px; width:445px">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/2.jpeg?raw=true" style="height:445px; width:445px">
</div>


In [38]:
def sig(z):
    return 1/(1+np.exp(-z))

In [39]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

# Initially choosing random values for weights and bias

In [111]:

weights = 2*np.random.random((2,1))-1  #pass shape as argument 
bias = 2*np.random.random(1)-1
lr = 0.1
weights,bias

(array([[-0.72505558],
        [-0.39473312]]),
 array([0.28071009]))

# finding Best values of weights and bias

## Error Calculation
<br>
<div style="display:flex ; width:1850px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/3.jpeg?raw=true" style="height:430px;width:440px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/4.jpeg?raw=true" style="height:430px;width:430px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/5.png?raw=true" style="height:430px;width:430px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/6.png?raw=true" style="height:430px;width:430px;">
</div>


## Matrix first_two and Matrix changes in Below code represents
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/7.png?raw=true" style="height:430px;width:450px;">


In [113]:

for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)

    first_term = output-Y  # output = Ypred
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)


    first_two = first_term*second_term
    first_two.shape


    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]



    weights = weights - lr*changes

    bias_change = 0.0
    for j in range(4):
            bias_change += first_two[j][0]*1

    bias = bias-lr*bias_change




(array([[6.26867964],
        [6.26867964]]),
 array([-9.49284861]),
 array([[7.53833604e-05],
        [3.82662637e-02],
        [3.82662637e-02],
        [9.54544944e-01]]))

# Using latest values of weights and bias for prediction

In [114]:
output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[6.26867964],
        [6.26867964]]),
 array([-9.49284861]),
 array([[7.53833604e-05],
        [3.82662637e-02],
        [3.82662637e-02],
        [9.54544944e-01]]))