In [2]:
import numpy as np

In [3]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

## Deriving derivative of sigmoid(z)

<br>

<div style="display:flex">
    <img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/1.png?raw=true" style="height:445px; width:445px">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/2.jpeg?raw=true" style="height:445px; width:445px">
</div>


In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

# Initially choosing random values for weights and bias

In [10]:

weights = 2*np.random.random((2,1))-1  #pass shape as argument 
bias = 2*np.random.random(1)-1
lr = 0.1
weights,bias

(array([[-0.61542689],
        [-0.10392218]]),
 array([-0.32764633]))

# finding Best values of weights and bias

## Error Calculation
<br>
<div style="display:flex ; width:1850px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/3.jpeg?raw=true" style="height:430px;width:440px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/4.jpeg?raw=true" style="height:430px;width:430px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/5.png?raw=true" style="height:430px;width:430px;">
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/6.png?raw=true" style="height:430px;width:430px;">
</div>


## Matrix first_two and Matrix changes in Below code represents
<img src="https://github.com/bhav380-2/ML-Algorithms/blob/main/Neural%20Networks/images/7.png?raw=true" style="height:430px;width:450px;">


In [7]:

for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)

    first_term = output-Y  # output = Ypred
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)


    first_two = first_term*second_term
    first_two.shape


    changes = np.array([[0.0],[0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]*output0[j][i]



    weights = weights - lr*changes

    bias_change = 0.0
    for j in range(4):
            bias_change += first_two[j][0]*1

    bias = bias-lr*bias_change




# Using latest values of weights and bias for prediction

In [8]:
output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[5.47964809],
        [5.47964807]]),
 array([-8.31216324]),
 array([[2.45452104e-04],
        [5.55921991e-02],
        [5.55922003e-02],
        [9.33834059e-01]]))

# optimizing code to use Vector Multiplication

In [11]:

for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights)+bias)

    first_term = output-Y  # output = Ypred
    input_for_last_layer = np.dot(output0,weights)+bias
    second_term = derivativeSig(input_for_last_layer)


    first_two = first_term*second_term
    first_two.shape


    changes = np.dot(output0.T,first_two)

    weights = weights - lr*changes

    bias_change = np.sum(first_two)
    
    bias = bias-lr*bias_change


output = sig(np.dot(X,weights)+bias)
weights,bias,output

(array([[5.47389317],
        [5.47389318]]),
 array([-8.3035565]),
 array([[2.47573239e-04],
        [5.57421165e-02],
        [5.57421161e-02],
        [9.33654459e-01]]))