In [13]:
import numpy as np

In [131]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,1,0]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [15]:
def sig(z):
    return 1/(1+np.exp(-z))

In [16]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

# Forward Propagation with 1 Hidden Layer

In [132]:
wh = 2*np.random.random((2,2))-1
bh = 2 * np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1
lr=0.1

# BackPropagation

In [182]:
for iter in range(10000):
#     print("hi")
    output0= X
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo)+bo
    output = sig(inputForOutputLayer)
    output

    first_term_output_layer = output-Y
    second_term_output_layer =   derivativeSig(inputForOutputLayer)

    first_two_output_layer = first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer,axis = 0,keepdims=True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims=True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr * changes_hidden
    bh = bh - lr*changes_hidden_bias

    
    
    
output0= X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden)

inputForOutputLayer = np.dot(outputHidden,wo)+bo
output = sig(inputForOutputLayer)
print("RESULT : ")
output,wh, bh,wo,bo


RESULT : 


(array([[0.01853459],
        [0.00678705],
        [0.96899457],
        [0.01648571]]),
 array([[-1.11572608, -4.91300686],
        [-0.24870082,  5.14437826]]),
 array([[-0.22244046,  2.01631259]]),
 array([[-0.27305039],
        [-8.84967977]]),
 array([[3.96183047]]))