In [13]:
import numpy as np

In [131]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,1,0]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [15]:
def sig(z):
    return 1/(1+np.exp(-z))

In [16]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

# Forward Propagation with 1 Hidden Layer

In [132]:
wh = 2*np.random.random((2,2))-1
bh = 2 * np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1
lr=0.1

In [133]:
for iter in range(10000):
#     print("hi")
    output0= X
    inputHidden = np.dot(output0,wh)+bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,wo)+bo
    output = sig(inputForOutputLayer)
    output

    first_term_output_layer = output-Y
    second_term_output_layer =   derivativeSig(inputForOutputLayer)

    first_two_output_layer = first_term_output_layer*second_term_output_layer
    
    first_term_hidden_layer = np.dot(first_two_output_layer,wo.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer=first_term_hidden_layer*second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer,axis = 0,keepdims=True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer,axis = 0,keepdims=True)

    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias

    wh = wh - lr * changes_hidden
    bh = bh - lr*changes_hidden_bias

    
output0= X
inputHidden = np.dot(output0,wh)+bh
outputHidden = sig(inputHidden)

inputForOutputLayer = np.dot(outputHidden,wo)+bo
output = sig(inputForOutputLayer)
output,wh, bh,wo,bo


(array([[0.02814324],
        [0.00989158],
        [0.95331533],
        [0.02470161]]),
 array([[-1.071134  , -4.60818801],
        [-0.26712797,  4.84077604]]),
 array([[-0.21377961,  1.85761127]]),
 array([[-0.24770533],
        [-8.07669255]]),
 array([[3.5552498]]))