In [16]:
import numpy as np
from sklearn import preprocessing

In [4]:
X = np.array([[1., -1., 2.],
              [2., 0., 0.],
              [0., 1., -1.]])

In [5]:
X_scaled = preprocessing.scale(X) # it will make mean 0 and variance 1

In [6]:
X_scaled.mean(axis = 0) # set mean to 0

array([0., 0., 0.])

In [7]:
X_scaled.std(axis=0) #set sttandard deviation to 1

array([1., 1., 1.])

In [8]:
y1_pred = pred(X_test,m,c)
scaler = preprocessing.StandardScaler() # used to scale testing data
scaler.fit(X)             # save parameters that were used to scale traingin data
scaler.transform(X)       # used to transform data # ''trial''

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [9]:
X_test = [[1,1,0]]  # array of testing data
scaler.transform(X_test) # scales testing data using parameters used while scaling training data

array([[ 0.        ,  1.22474487, -0.26726124]])

In [36]:
data = [[6,9],[1,4],[2,8],[2,1]]
scaler = preprocessing.StandardScaler()
scaler.fit(data)
first = scaler.transform(data)

second = scaler.transform([[2,13],[1,4],[10,7],[1,9]])
print(first.sum())
print(second.sum())

0.0
4.99808969331922
